= Update Klayr Core (Docker)
Christopher Braithwaite <christopher.braithwaite@lightcurve.io>
:description: How to update up a Klayr Core node with Docker.
:toc:
// Settings
// External URLs
:url_core_releases: https://github.com/KlayrHQ/klayr-core/releases
:url_rel_notes: https://github.com/KlayrHQ/klayr-core/releases
:url_tags: https://github.com/KlayrHQ/klayr-core/tags

This page describes how to update the Docker image-based container in Klayr Core.
Klayr Core version 4 does not have any external dependencies, and hence does not require using `docker-compose`.


To upgrade the Docker container to a desired version, please follow one of the two options below.
To find all the tagged versions for Klayr Core, please check the {url_tags}[available tags] on GitHub.
[tabs]
====
Option A - Download pre-built images from DockerHub::
+
--
. Stop Klayr Core
+
----
make stop
----

. Manually download the image from `DockerHub`.
+

[source,sh]
----
docker image pull klayr-core
----
NOTE: To download a specific version of Klayr Core, please include the tag after `klayr-core` in the above command. For example, `klayr-core:4.1.1`

. Start Klayr Core in the containers.
+
----
make start ARGS="-n mainnet --api-ws"
----
NOTE: Please customize `ARGS` as per your requirements.
--
Option B - Build images locally ::
+
--
Build the images locally using the following steps.
Navigate inside the klayr-core root folder, and execute the following commands.

. Stop Klayr Core
+
----
make stop
----

. Checkout the version with *`git checkout <tag>`*
+
----
git checkout v4.1.1
----

. Build the required updated Docker image
+
----
make build-image
----

. Start Klayr Core in the container
+
----
make start ARGS="-n mainnet --api-ws"
----
NOTE: Please customize the `ARGS` as per your requirements.
--
====

